version: "3"
services:
  app:
    container_name: account-app
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
      - MONGOURL=mongodb://mongo:27017/accountApp
    volumes:
      - .:/app
      - /usr/src/app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"